use enum_primitive_derive::Primitive;
use factorio_serialize_derive::ReplayReadWriteEnumU8;
use num_traits::{FromPrimitive, ToPrimitive};

// Version: 1.1.107
// Extraction method: util::export_prototypes
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReplayReadWriteEnumU8)]
pub enum Decorative {
  BrownHairyGrass = 1,
  GreenHairyGrass = 2,
  BrownCarpetGrass = 3,
  GreenCarpetGrass = 4,
  GreenSmallGrass = 5,
  MuddyStump = 6,
  GreenAsterisk = 7,
  BrownAsteriskMini = 8,
  GreenAsteriskMini = 9,
  BrownAsterisk = 10,
  RedAsterisk = 11,
  EnemyDecal = 12,
  EnemyDecalTransparent = 13,
  DarkMudDecal = 14,
  LightMudDecal = 15,
  NuclearGroundPatch = 16,
  PubertyDecal = 17,
  RedDesertDecal = 18,
  SandDecal = 19,
  SandDuneDecal = 20,
  GreenPita = 21,
  RedPita = 22,
  GreenCroton = 23,
  RedCroton = 24,
  GreenPitaMini = 25,
  BrownFluff = 26,
  BrownFluffDry = 27,
  GreenDesertBush = 28,
  RedDesertBush = 29,
  WhiteDesertBush = 30,
  GarballoMiniDry = 31,
  Garballo = 32,
  GreenBushMini = 33,
  LichenDecal = 34,
  ShroomDecal = 35,
  WormsDecal = 36,
  RockMedium = 37,
  RockSmall = 38,
  RockTiny = 39,
  BigShipWreckGrass = 40,
  SandRockMedium = 41,
  SandRockSmall = 42,
  SmallShipWreckGrass = 43,
}
impl Decorative {
  pub fn name(self) -> &'static str {
    match self {
      Decorative::BrownHairyGrass => "brown-hairy-grass",
      Decorative::GreenHairyGrass => "green-hairy-grass",
      Decorative::BrownCarpetGrass => "brown-carpet-grass",
      Decorative::GreenCarpetGrass => "green-carpet-grass",
      Decorative::GreenSmallGrass => "green-small-grass",
      Decorative::MuddyStump => "muddy-stump",
      Decorative::GreenAsterisk => "green-asterisk",
      Decorative::BrownAsteriskMini => "brown-asterisk-mini",
      Decorative::GreenAsteriskMini => "green-asterisk-mini",
      Decorative::BrownAsterisk => "brown-asterisk",
      Decorative::RedAsterisk => "red-asterisk",
      Decorative::EnemyDecal => "enemy-decal",
      Decorative::EnemyDecalTransparent => "enemy-decal-transparent",
      Decorative::DarkMudDecal => "dark-mud-decal",
      Decorative::LightMudDecal => "light-mud-decal",
      Decorative::NuclearGroundPatch => "nuclear-ground-patch",
      Decorative::PubertyDecal => "puberty-decal",
      Decorative::RedDesertDecal => "red-desert-decal",
      Decorative::SandDecal => "sand-decal",
      Decorative::SandDuneDecal => "sand-dune-decal",
      Decorative::GreenPita => "green-pita",
      Decorative::RedPita => "red-pita",
      Decorative::GreenCroton => "green-croton",
      Decorative::RedCroton => "red-croton",
      Decorative::GreenPitaMini => "green-pita-mini",
      Decorative::BrownFluff => "brown-fluff",
      Decorative::BrownFluffDry => "brown-fluff-dry",
      Decorative::GreenDesertBush => "green-desert-bush",
      Decorative::RedDesertBush => "red-desert-bush",
      Decorative::WhiteDesertBush => "white-desert-bush",
      Decorative::GarballoMiniDry => "garballo-mini-dry",
      Decorative::Garballo => "garballo",
      Decorative::GreenBushMini => "green-bush-mini",
      Decorative::LichenDecal => "lichen-decal",
      Decorative::ShroomDecal => "shroom-decal",
      Decorative::WormsDecal => "worms-decal",
      Decorative::RockMedium => "rock-medium",
      Decorative::RockSmall => "rock-small",
      Decorative::RockTiny => "rock-tiny",
      Decorative::BigShipWreckGrass => "big-ship-wreck-grass",
      Decorative::SandRockMedium => "sand-rock-medium",
      Decorative::SandRockSmall => "sand-rock-small",
      Decorative::SmallShipWreckGrass => "small-ship-wreck-grass",
    }
  }
  pub fn from_name(name: &str) -> Decorative {
    match name {
      "brown-hairy-grass" => Decorative::BrownHairyGrass,
      "green-hairy-grass" => Decorative::GreenHairyGrass,
      "brown-carpet-grass" => Decorative::BrownCarpetGrass,
      "green-carpet-grass" => Decorative::GreenCarpetGrass,
      "green-small-grass" => Decorative::GreenSmallGrass,
      "muddy-stump" => Decorative::MuddyStump,
      "green-asterisk" => Decorative::GreenAsterisk,
      "brown-asterisk-mini" => Decorative::BrownAsteriskMini,
      "green-asterisk-mini" => Decorative::GreenAsteriskMini,
      "brown-asterisk" => Decorative::BrownAsterisk,
      "red-asterisk" => Decorative::RedAsterisk,
      "enemy-decal" => Decorative::EnemyDecal,
      "enemy-decal-transparent" => Decorative::EnemyDecalTransparent,
      "dark-mud-decal" => Decorative::DarkMudDecal,
      "light-mud-decal" => Decorative::LightMudDecal,
      "nuclear-ground-patch" => Decorative::NuclearGroundPatch,
      "puberty-decal" => Decorative::PubertyDecal,
      "red-desert-decal" => Decorative::RedDesertDecal,
      "sand-decal" => Decorative::SandDecal,
      "sand-dune-decal" => Decorative::SandDuneDecal,
      "green-pita" => Decorative::GreenPita,
      "red-pita" => Decorative::RedPita,
      "green-croton" => Decorative::GreenCroton,
      "red-croton" => Decorative::RedCroton,
      "green-pita-mini" => Decorative::GreenPitaMini,
      "brown-fluff" => Decorative::BrownFluff,
      "brown-fluff-dry" => Decorative::BrownFluffDry,
      "green-desert-bush" => Decorative::GreenDesertBush,
      "red-desert-bush" => Decorative::RedDesertBush,
      "white-desert-bush" => Decorative::WhiteDesertBush,
      "garballo-mini-dry" => Decorative::GarballoMiniDry,
      "garballo" => Decorative::Garballo,
      "green-bush-mini" => Decorative::GreenBushMini,
      "lichen-decal" => Decorative::LichenDecal,
      "shroom-decal" => Decorative::ShroomDecal,
      "worms-decal" => Decorative::WormsDecal,
      "rock-medium" => Decorative::RockMedium,
      "rock-small" => Decorative::RockSmall,
      "rock-tiny" => Decorative::RockTiny,
      "big-ship-wreck-grass" => Decorative::BigShipWreckGrass,
      "sand-rock-medium" => Decorative::SandRockMedium,
      "sand-rock-small" => Decorative::SandRockSmall,
      "small-ship-wreck-grass" => Decorative::SmallShipWreckGrass,
      name => panic!("unknown Decorative \"{name}\""),
    }
  }
}