[package]
name = "factorio-replay-tool"
version = "0.1.0"
authors = ["MrWint <mrwint42@gmail.com>"]
edition = "2021"

[dependencies]
byteorder = "*"
enum-primitive-derive = "*"
num-traits = "*"
zip = "*"
heck = "*"
factorio-serialize = { path = "factorio-serialize" }
