[package]
name = "factorio-serialize-derive"
version = "0.1.0"
authors = ["MrWint <mrwint42@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "*"
proc-macro2 = "1.0"
quote = "*"
