[package]
name = "factorio-serialize-derive"
version = "0.1.0"
authors = ["MrWint <mrwint42@gmail.com>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "*", features = ["extra-traits"] }
proc-macro2 = "1.0"
quote = "*"
