[package]
name = "factorio-serialize"
version = "0.1.0"
authors = ["MrWint <mrwint42@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "*"
factorio-serialize-derive = { path = "factorio-serialize-derive" }
