use crate as factorio_serialize; // import own name to make proc macros work
use enum_primitive_derive::Primitive;
use factorio_serialize::{ReadWriteEnumU8, ReadWriteEnumU16};
use num_traits::{FromPrimitive, ToPrimitive};


// Source: disassembly AdminActionData::Type"
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum AdminActionDataType {
  None = 0,
  Add = 1,
  Kick = 2,
  Ban = 3,
  Unban = 4,
  Promote = 5,
  Demote = 6,
  Purge = 7,
  Mute = 8,
  Unmute = 9,
  Whitelist = 10,
  UnWhitelist = 11,
  ChangePermissionGroup = 12,
  Delete = 13,
}

// Source: disassembly AllowedCommands::Enum"
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum AllowedCommands {
  True = 0,
  False = 1,
  AdminsOnly = 2,
}

// Source: disassembly ArithmeticCombinatorParameters::Operation
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum ArithmeticCombinatorParametersOperation {
  Multiply = 0,
  Divide = 1,
  Add = 2,
  Subtract = 3,
  Modulo = 4,
  Power = 5,
  LeftShift = 6,
  RightShift = 7,
  AND = 8,
  OR = 9,
  XOR = 10,
}

// Source: disassembly Comparison::Enum
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum Comparison {
  GreaterThan = 0,
  LessThan = 1,
  Equals = 2,
  GreaterOrEqual = 3,
  LessOrEqual = 4,
  NotEqual = 5,
}

// Source: disassembly Difficulty::Enum
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum Difficulty {
  Nothing = 0,
  Easy = 1,
  Normal = 2,
  Hard = 3,
}

// Source: defines.direction
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum Direction {
  N = 0,
  NE = 1,
  E = 2,
  SE = 3,
  S = 4,
  SW = 5,
  W = 6,
  NW = 7,
  None = 8,
}

// Source: disassembly DisconnectReason::Enum
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum DisconnectReason {
  Quit = 0,
  Dropped = 1,
  Reconnect = 2,
  WrongInput = 3,
  DesyncLimitReached = 4,
  CantKeepUp = 5,
  AFK = 6,
  Kicked = 7,
  KickedAndDeleted = 8,
  Banned = 9,
  SwitchingServers = 10,
}

// Source: disassembly EditPermissionGroupType
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum EditPermissionGroupType {
  Nothing = 0,
  AddPermission = 1,
  RemovePermission = 2,
  EnableAllPermissions = 3,
  DisableAllPermissions = 4,
  AddPlayer = 5,
  RemovePlayer = 6,
  EditGroupName = 7,
}

// Source: disassembly EnergyPropertyType
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum EnergyPropertyType {
  BufferSize = 0,
  PowerProduction = 1,
  PowerUsage = 2,
}

// Source: disassembly ActionData::EquipmentData::Type
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum EquipmentDataType {
  CursorTransfer = 0,
  StandardTransfer = 1,
  TransferAllOfType = 2,
  TransferHalfOfType = 3,
  Place = 4,
  Open = 5,
}

// Source: disassembly GameRenderMode
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum GameRenderMode {
  Nothing = 0,
  Game = 1,
  Chart = 2,
  ChartZoomedIn = 3,
}

// TransportBeltControlBehavior::ContentsReadMode and InserterControlBehavior::HandReadMode
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum HandOrContentsReadMode {
  PulseMode = 0,
  HoldMode = 1,
}

// Source: disassembly InfinityFilter::Mode
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum InfinityFilterMode {
  KeepAtLeast = 0,
  KeepAtMost = 1,
  KeepExactly = 2,
}

// Version: 0.17.69
// Extraction method: disassembly InputAction::actionTypeToString
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum InputActionType {
  Nothing = 0x00,
  StopWalking = 0x01,
  BeginMining = 0x02,
  StopMining = 0x03,
  ToggleDriving = 0x04,
  OpenGui = 0x05,
  CloseGui = 0x06,
  OpenCharacterGui = 0x07,
  ConnectRollingStock = 0x08,
  DisconnectRollingStock = 0x09,
  SelectedEntityCleared = 0x0a,
  CleanCursorStack = 0x0b,
  ResetAssemblingMachine = 0x0c,
  OpenTechnologyGui = 0x0d,
  LaunchRocket = 0x0e,
  OpenBlueprintLibraryGui = 0x0f,
  OpenProductionGui = 0x10,
  OpenKillsGui = 0x11,
  StopRepair = 0x12,
  CancelNewBlueprint = 0x13,
  CloseBlueprintRecord = 0x14,
  CopyEntitySettings = 0x15,
  PasteEntitySettings = 0x16,
  DestroyOpenedItem = 0x17,
  UpgradeOpenedBlueprint = 0x18,
  ToggleShowEntityInfo = 0x19,
  SingleplayerInit = 0x1a,
  MultiplayerInit = 0x1b,
  SwitchToRenameStopGui = 0x1c,
  OpenBonusGui = 0x1d,
  OpenTrainsGui = 0x1e,
  OpenAchievementsGui = 0x1f,
  OpenTutorialsGui = 0x20,
  CycleBlueprintBookForwards = 0x21,
  CycleBlueprintBookBackwards = 0x22,
  CycleClipboardForwards = 0x23,
  CycleClipboardBackwards = 0x24,
  StopMovementInTheNextTick = 0x25,
  ToggleEnableVehicleLogisticsWhileMoving = 0x26,
  ToggleDeconstructionItemEntityFilterMode = 0x27,
  ToggleDeconstructionItemTileFilterMode = 0x28,
  OpenLogisticGui = 0x29,
  CancelDropBlueprintRecord = 0x2a,
  SelectNextValidGun = 0x2b,
  ToggleMapEditor = 0x2c,
  DeleteBlueprintLibrary = 0x2d,
  GameCreatedFromScenario = 0x2e,
  ActivateCopy = 0x2f,
  ActivateCut = 0x30,
  ActivatePaste = 0x31,
  Undo = 0x32,
  TogglePersonalRoboport = 0x33,
  ToggleEquipmentMovementBonus = 0x34,
  StopBuildingByMoving = 0x35,
  DropItem = 0x36,
  BuildItem = 0x37,
  StartWalking = 0x38,
  BeginMiningTerrain = 0x39,
  ChangeRidingState = 0x3a,
  OpenItem = 0x3b,
  OpenModItem = 0x3c,
  OpenEquipment = 0x3d,
  CursorTransfer = 0x3e,
  CursorSplit = 0x3f,
  StackTransfer = 0x40,
  InventoryTransfer = 0x41,
  CheckCRCHeuristic = 0x42,
  Craft = 0x43,
  WireDragging = 0x44,
  ChangeShootingState = 0x45,
  SetupAssemblingMachine = 0x46,
  SelectedEntityChanged = 0x47,
  SmartPipette = 0x48,
  StackSplit = 0x49,
  InventorySplit = 0x4a,
  CancelCraft = 0x4b,
  SetFilter = 0x4c,
  CheckCRC = 0x4d,
  SetCircuitCondition = 0x4e,
  SetSignal = 0x4f,
  StartResearch = 0x50,
  SetLogisticFilterItem = 0x51,
  SetLogisticFilterSignal = 0x52,
  SetCircuitModeOfOperation = 0x53,
  GuiClick = 0x54,
  GuiConfirmed = 0x55,
  WriteToConsole = 0x56,
  MarketOffer = 0x57,
  AddTrainStation = 0x58,
  ChangeTrainStopStation = 0x59,
  ChangeActiveItemGroupForCrafting = 0x5a,
  GuiTextChanged = 0x5b,
  GuiCheckedStateChanged = 0x5c,
  GuiSelectionStateChanged = 0x5d,
  GuiSelectedTabChanged = 0x5e,
  GuiValueChanged = 0x5f,
  GuiSwitchStateChanged = 0x60,
  GuiLocationChanged = 0x61,
  PlaceEquipment = 0x62,
  TakeEquipment = 0x63,
  UseItem = 0x64,
  UseArtilleryRemote = 0x65,
  SetInventoryBar = 0x66,
  ChangeActiveItemGroupForFilters = 0x67,
  MoveOnZoom = 0x68,
  StartRepair = 0x69,
  Deconstruct = 0x6a,
  Upgrade = 0x6b,
  Copy = 0x6c,
  AlternativeCopy = 0x6d,
  SelectBlueprintEntities = 0x6e,
  AltSelectBlueprintEntities = 0x6f,
  SetupBlueprint = 0x70,
  SetupSingleBlueprintRecord = 0x71,
  SetSingleBlueprintRecordIcon = 0x72,
  OpenBlueprintRecord = 0x73,
  CloseBlueprintBook = 0x74,
  ChangeSingleBlueprintRecordLabel = 0x75,
  GrabBlueprintRecord = 0x76,
  DropBlueprintRecord = 0x77,
  DeleteBlueprintRecord = 0x78,
  CreateBlueprintLike = 0x79,
  CreateBlueprintLikeStackTransfer = 0x7a,
  UpdateBlueprintShelf = 0x7b,
  TransferBlueprint = 0x7c,
  TransferBlueprintImmediately = 0x7d,
  ChangeBlueprintBookRecordLabel = 0x7e,
  RemoveCables = 0x7f,
  ExportBlueprint = 0x80,
  ImportBlueprint = 0x81,
  PlayerJoinGame = 0x82,
  CancelDeconstruct = 0x83,
  CancelUpgrade = 0x84,
  ChangeArithmeticCombinatorParameters = 0x85,
  ChangeDeciderCombinatorParameters = 0x86,
  ChangeProgrammableSpeakerParameters = 0x87,
  ChangeProgrammableSpeakerAlertParameters = 0x88,
  ChangeProgrammableSpeakerCircuitParameters = 0x89,
  BuildTerrain = 0x8a,
  ChangeTrainWaitCondition = 0x8b,
  ChangeTrainWaitConditionData = 0x8c,
  CustomInput = 0x8d,
  ChangeItemLabel = 0x8e,
  BuildRail = 0x8f,
  CancelResearch = 0x90,
  SelectArea = 0x91,
  AltSelectArea = 0x92,
  ServerCommand = 0x93,
  ClearSelectedBlueprint = 0x94,
  ClearSelectedDeconstructionItem = 0x95,
  ClearSelectedUpgradeItem = 0x96,
  SetLogisticTrashFilterItem = 0x97,
  SetInfinityContainerFilterItem = 0x98,
  SetInfinityPipeFilter = 0x99,
  ModSettingsChanged = 0x9a,
  SetEntityEnergyProperty = 0x9b,
  EditCustomTag = 0x9c,
  EditPermissionGroup = 0x9d,
  ImportBlueprintString = 0x9e,
  ImportPermissionsString = 0x9f,
  ReloadScript = 0xA0,
  ReloadScriptDataTooLarge = 0xA1,
  GuiElemChanged = 0xA2,
  BlueprintTransferQueueUpdate = 0xA3,
  DragTrainSchedule = 0xA4,
  DragTrainWaitCondition = 0xA5,
  SelectItem = 0xA6,
  SelectEntitySlot = 0xA7,
  SelectTileSlot = 0xA8,
  SelectMapperSlot = 0xA9,
  DisplayResolutionChanged = 0xAA,
  QuickBarSetSlot = 0xAB,
  QuickBarPickSlot = 0xAC,
  QuickBarSetSelectedPage = 0xAD,
  PlayerLeaveGame = 0xAE,
  MapEditorAction = 0xAF,
  PutSpecialItemInMap = 0xB0,
  ChangeMultiplayerConfig = 0xB1,
  AdminAction = 0xB2,
  LuaShortcut = 0xB3,
  TranslateString = 0xB4,
  ChangePickingState = 0xB5,
  SelectedEntityChangedVeryClose = 0xB6,
  SelectedEntityChangedVeryClosePrecise = 0xB7,
  SelectedEntityChangedRelative = 0xB8,
  SelectedEntityChangedBasedOnUnitNumber = 0xB9,
  SetAutosortInventory = 0xBA,
  SetAutoLaunchRocket = 0xBB,
  SwitchConstantCombinatorState = 0xBC,
  SwitchPowerSwitchState = 0xBD,
  SwitchInserterFilterModeState = 0xBE,
  SwitchConnectToLogisticNetwork = 0xBF,
  SetBehaviorMode = 0xC0,
  FastEntityTransfer = 0xC1,
  RotateEntity = 0xC2,
  FastEntitySplit = 0xC3,
  SetTrainStopped = 0xC4,
  ChangeControllerSpeed = 0xC5,
  SetAllowCommands = 0xC6,
  SetResearchFinishedStopsGame = 0xC7,
  SetInserterMaxStackSize = 0xC8,
  OpenTrainGui = 0xC9,
  SetEntityColor = 0xCA,
  SetDeconstructionItemTreesAndRocksOnly = 0xCB,
  SetDeconstructionItemTileSelectionMode = 0xCC,
  DropToBlueprintBook = 0xCD,
  DeleteCustomTag = 0xCE,
  DeletePermissionGroup = 0xCF,
  AddPermissionGroup = 0xD0,
  SetInfinityContainerRemoveUnfilteredItems = 0xD1,
  SetCarWeaponsControl = 0xD2,
  SetRequestFromBuffers = 0xD3,
  ChangeActiveQuickBar = 0xD4,
  OpenPermissionsGui = 0xD5,
  DisplayScaleChanged = 0xD6,
  SetSplitterPriority = 0xD7,
  GrabInternalBlueprintFromText = 0xD8,
  SetHeatInterfaceTemperature = 0xD9,
  SetHeatInterfaceMode = 0xDA,
  OpenTrainStationGui = 0xDB,
  RemoveTrainStation = 0xDC,
  GoToTrainStation = 0xDD,
  RenderModeChanged = 0xDE,
}

// Source: disassembly Inserter::FilterMode"
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum InserterFilterMode {
  Whitelist = 0,
  Blacklist = 1,
}

// Source: disassembly LocalisedString::Mode
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum LocalisedStringMode {
  Empty = 0,
  Translation = 1,
  Literal = 2,
  LiteralTranslation = 3,
}

// Source: disassembly agui::MouseButton
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum MouseButton {
  None = 0,
  Left = 1,
  Right = 2,
  Middle = 3,
  Button4 = 4,
  Button5 = 5,
  Button6 = 6,
  Button7 = 7,
  Button8 = 8,
  Button9 = 9,
  LeftAndRight = 10,
  All = 11,
}

// Source: defines.riding.acceleration
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum RailBuildingMode {
  Manual = 0,
  Ghost = 1,
}

// Source: defines.riding.acceleration
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum RidingAccelerationState {
  Nothing = 0,
  Accelerating = 1,
  Braking = 2,
  Reversing = 3,
}

// Source: defines.riding.direction
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum RidingDirection {
  Left = 0,
  Straight = 1,
  Right = 2,
}

// Source: disassembly SignalID::ContainedType
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum SignalIdType {
  Item = 0,
  Fluid = 1,
  VirtualSignal = 2,
}

// Source: disassembly ShootingState::State
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum ShootingStateState {
  NotShooting = 0,
  ShootingEnemies = 1,
  ShootingSelected = 2,
}

// Source: disassembly enum ItemStackTargetSpecification::Source
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum SlotSource {
  Empty = 0,
  PlayerInventory = 1,
  PlayerExternalInventory = 2,
  PlayerCursor = 3,
  EntityInventory = 4,
  VehicleInventory = 5,
  OpenedItemInventory = 6,
  OpenedEquipmentInventory = 7,
  OpenedOtherPlayerInventory = 8,
  OpenedOtherPlayerCursor = 9,
  OpenedEntityCursor = 0xa,
  PlayerQuickBar = 0xb,
  OpenedEditorCharacterInventory = 0xc,
  OpenedEditorCharacterCursor = 0xd,
}

// Source: disassembly enum ItemStackTargetSpecification::Target
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum SlotTarget {
  Default = 0,
  EquipmentGrid = 1,
}

// Source: disassembly enum Splitter::Priority
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum SplitterPriority {
  Left = 0,
  None = 1,
  Right = 2,
}

// Source: disassembly agui::SwitchState
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum SwitchState {
  Left = 0,
  Right = 1,
  None = 2,
}

// Source: disassembly ActionData::TrainWaitCondition::Action
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum TrainWaitConditionAction {
  Add = 0,
  Remove = 1,
  Toggle = 2,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum TransferDirection {
  Out = 0,
  In = 1,
}

// Source: disassembly WaitCondition::ComparisonType
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum WaitConditionComparisonType {
  And = 0,
  Or = 1,
}

// Source: disassembly WaitCondition::ConditionType
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum WaitConditionType {
  Time = 0,
  Full = 1,
  Empty = 2,
  ItemCount = 3,
  Circuit = 4,
  Inactivity = 5,
  RobotsInactive = 6,
  FluidCount = 7,
  PassengerPresent = 8,
  PassengerNotPresent = 9,
}

/////////
// IDs //
/////////

// Version: 0.17.69
// Alt method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum Achievement {
  GettingOnTrack = 1,
  EcoUnfriendly = 2,
  TechManiac = 3,
  SmokeMeAKipperIWillBeBackForBreakfast = 4,
  ItStinksAndTheyDontLikeIt = 5,
  AutomatedConstruction = 6,
  YouAreDoingItRight = 7,
  AutomatedCleanup = 8,
  YouHaveGotAPackage = 9,
  DeliveryService = 10,
  TransFactorioExpress = 11,
  WatchYourStep = 12,
  Golem = 13,
  GettingOnTrackLikeAPro = 14,
  MassProduction1 = 15,
  MassProduction2 = 16,
  MassProduction3 = 17,
  CircuitVeteran1 = 18,
  CircuitVeteran2 = 19,
  CircuitVeteran3 = 20,
  ComputerAge1 = 21,
  ComputerAge2 = 22,
  ComputerAge3 = 23,
  IronThrone1 = 24,
  IronThrone2 = 25,
  IronThrone3 = 26,
  Solaris = 27,
  Steamrolled = 28,
  Pyromaniac = 29,
  RunForrestRun = 30,
  Minions = 31,
  LazyBastard = 32,
  SteamAllTheWay = 33,
  RainingBullets = 34,
  LogisticNetworkEmbargo = 35,
  NoTimeForChitchat = 36,
  ThereIsNoSpoon = 37,
  SoLongAndThanksForAllTheFish = 38,
}

// Version: 0.17.69
// Alt method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum Decorative {
  BrownHairyGrass = 1,
  GreenHairyGrass = 2,
  BrownCarpetGrass = 3,
  GreenCarpetGrass = 4,
  GreenSmallGrass = 5,
  GreenAsterisk = 6,
  BrownAsteriskMini = 7,
  GreenAsteriskMini = 8,
  BrownAsterisk = 9,
  RedAsterisk = 10,
  DarkMudDecal = 11,
  LightMudDecal = 12,
  PubertyDecal = 13,
  RedDesertDecal = 14,
  SandDecal = 15,
  SandDuneDecal = 16,
  GreenPita = 17,
  RedPita = 18,
  GreenCroton = 19,
  RedCroton = 20,
  GreenPitaMini = 21,
  BrownFluff = 22,
  BrownFluffDry = 23,
  GreenDesertBush = 24,
  RedDesertBush = 25,
  WhiteDesertBush = 26,
  GarballoMiniDry = 27,
  Garballo = 28,
  GreenBushMini = 29,
  Lichen = 30,
  RockMedium = 31,
  RockSmall = 32,
  RockTiny = 33,
  BigShipWreckGrass = 34,
  SandRockMedium = 35,
  SandRockSmall = 36,
  SmallShipWreckGrass = 37,
}

// Version: 0.17.69
// Extraction method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum Entity {
  WoodenChest = 1,
  IronChest = 2,
  SteelChest = 3,
  CompilatronChest = 4,
  StorageTank = 5,
  TransportBelt = 6,
  FastTransportBelt = 7,
  ExpressTransportBelt = 8,
  UndergroundBelt = 9,
  FastUndergroundBelt = 10,
  ExpressUndergroundBelt = 11,
  Splitter = 12,
  FastSplitter = 13,
  ExpressSplitter = 14,
  Loader = 15,
  FastLoader = 16,
  ExpressLoader = 17,
  BurnerInserter = 18,
  Inserter = 19,
  LongHandedInserter = 20,
  FastInserter = 21,
  FilterInserter = 22,
  StackInserter = 23,
  StackFilterInserter = 24,
  SmallElectricPole = 25,
  MediumElectricPole = 26,
  BigElectricPole = 27,
  Substation = 28,
  Pipe = 29,
  PipeToGround = 30,
  Pump = 31,
  CurvedRail = 32,
  StraightRail = 33,
  TrainStop = 34,
  RailSignal = 35,
  RailChainSignal = 36,
  Locomotive = 37,
  CargoWagon = 38,
  FluidWagon = 39,
  ArtilleryWagon = 40,
  Car = 41,
  Tank = 42,
  LogisticRobot = 43,
  ConstructionRobot = 44,
  LogisticChestActiveProvider = 45,
  LogisticChestPassiveProvider = 46,
  LogisticChestStorage = 47,
  LogisticChestBuffer = 48,
  LogisticChestRequester = 49,
  Roboport = 50,
  SmallLamp = 51,
  ArithmeticCombinator = 52,
  DeciderCombinator = 53,
  ConstantCombinator = 54,
  PowerSwitch = 55,
  ProgrammableSpeaker = 56,
  Boiler = 57,
  SteamEngine = 58,
  SteamTurbine = 59,
  SolarPanel = 60,
  Accumulator = 61,
  NuclearReactor = 62,
  HeatExchanger = 63,
  HeatPipe = 64,
  BurnerMiningDrill = 65,
  ElectricMiningDrill = 66,
  OffshorePump = 67,
  Pumpjack = 68,
  StoneFurnace = 69,
  SteelFurnace = 70,
  ElectricFurnace = 71,
  AssemblingMachine1 = 72,
  AssemblingMachine2 = 73,
  AssemblingMachine3 = 74,
  OilRefinery = 75,
  ChemicalPlant = 76,
  Centrifuge = 77,
  Lab = 78,
  Beacon = 79,
  CrashSiteElectricPole = 80,
  CrashSiteAssemblingMachine1Broken = 81,
  CrashSiteAssemblingMachine1Repaired = 82,
  CrashSiteAssemblingMachine2Broken = 83,
  CrashSiteAssemblingMachine2Repaired = 84,
  CrashSiteChest1 = 85,
  CrashSiteChest2 = 86,
  CrashSiteGenerator = 87,
  CrashSiteLabBroken = 88,
  CrashSiteLabRepaired = 89,
  LandMine = 90,
  StoneWall = 91,
  Gate = 92,
  GunTurret = 93,
  LaserTurret = 94,
  FlamethrowerTurret = 95,
  ArtilleryTurret = 96,
  Radar = 97,
  RocketSilo = 98,
  InfinityChest = 99,
  SimpleEntityWithForce = 100,
  SimpleEntityWithOwner = 101,
  ElectricEnergyInterface = 102,
  HeatInterface = 103,
  InfinityPipe = 104,
  PlayerPort = 105,
  Cliff = 106,
  Character = 107,
  Fish = 108,
  Tree01 = 109,
  Tree02 = 110,
  Tree03 = 111,
  Tree04 = 112,
  Tree05 = 113,
  Tree09 = 114,
  Tree02Red = 115,
  Tree07 = 116,
  Tree06 = 117,
  Tree06Brown = 118,
  Tree09Brown = 119,
  Tree09Red = 120,
  Tree08 = 121,
  Tree08Brown = 122,
  Tree08Red = 123,
  DeadDryHairyTree = 124,
  DeadGreyTrunk = 125,
  DeadTreeDesert = 126,
  DryHairyTree = 127,
  DryTree = 128,
  RockHuge = 129,
  RockBig = 130,
  SmallBiterCorpse = 131,
  MediumBiterCorpse = 132,
  BehemothBiterCorpse = 133,
  BigBiterCorpse = 134,
  BiterSpawnerCorpse = 135,
  BehemothSpitterCorpse = 136,
  BigSpitterCorpse = 137,
  MediumSpitterCorpse = 138,
  SmallSpitterCorpse = 139,
  SpitterSpawnerCorpse = 140,
  SmallWormCorpse = 141,
  MediumWormCorpse = 142,
  BigWormCorpse = 143,
  BehemothWormCorpse = 144,
  Remnants1x2 = 145,
  AccumulatorRemnants = 146,
  ArithmeticCombinatorRemnants = 147,
  ArtilleryTurretRemnants = 148,
  BigElectricPoleRemnants = 149,
  BoilerRemnants = 150,
  BurnerInserterRemnants = 151,
  BurnerMiningDrillRemnants = 152,
  CentrifugeRemnants = 153,
  ConstantCombinatorRemnants = 154,
  DeciderCombinatorRemnants = 155,
  ExpressSplitterRemnants = 156,
  ExpressTransportBeltRemnants = 157,
  ExpressUndergroundBeltRemnants = 158,
  FastInserterRemnants = 159,
  FastSplitterRemnants = 160,
  FastTransportBeltRemnants = 161,
  FastUndergroundBeltRemnants = 162,
  FilterInserterRemnants = 163,
  FlamethrowerTurretRemnants = 164,
  GunTurretRemnants = 165,
  HeatPipeRemnants = 166,
  InserterRemnants = 167,
  LabRemnants = 168,
  LampRemnants = 169,
  LaserTurretRemnants = 170,
  LongHandedInserterRemnants = 171,
  MediumElectricPoleRemnants = 172,
  NuclearReactorRemnants = 173,
  PipeRemnants = 174,
  PumpRemnants = 175,
  RadarRemnants = 176,
  RoboportRemnants = 177,
  SmallElectricPoleRemnants = 178,
  SmallGenericRemnants = 179,
  SolarPanelRemnants = 180,
  SplitterRemnants = 181,
  StackFilterInserterRemnants = 182,
  StackInserterRemnants = 183,
  SteamEngineRemnants = 184,
  SteamTurbineRemnants = 185,
  SubstationRemnants = 186,
  TrainStopRemnants = 187,
  TransportBeltRemnants = 188,
  UndergroundBeltRemnants = 189,
  CarRemnants = 190,
  MediumRemnants = 191,
  MediumSmallRemnants = 192,
  OilRefineryRemnants = 193,
  PumpjackRemnants = 194,
  RailChainSignalRemnants = 195,
  RailSignalRemnants = 196,
  RocketSiloGenericRemnants = 197,
  SmallRemnants = 198,
  StoneFurnaceRemnants = 199,
  StorageTankRemnants = 200,
  TankRemnants = 201,
  BigRemnants = 202,
  StraightRailRemnants = 203,
  CurvedRailRemnants = 204,
  SmallScorchmark = 205,
  Tree01Stump = 206,
  Tree02Stump = 207,
  Tree03Stump = 208,
  Tree04Stump = 209,
  Tree05Stump = 210,
  Tree06Stump = 211,
  Tree07Stump = 212,
  Tree08Stump = 213,
  Tree09Stump = 214,
  WallRemnants = 215,
  SandRockBig = 216,
  BigShipWreck1 = 217,
  BigShipWreck2 = 218,
  BigShipWreck3 = 219,
  MediumShipWreck = 220,
  MineableWreckage = 221,
  SmallShipWreck = 222,
  Compilatron = 223,
  SmallBiter = 224,
  MediumBiter = 225,
  BigBiter = 226,
  BehemothBiter = 227,
  SmallWormTurret = 228,
  MediumWormTurret = 229,
  SmallSpitter = 230,
  BigWormTurret = 231,
  MediumSpitter = 232,
  BehemothWormTurret = 233,
  BigSpitter = 234,
  BiterSpawner = 235,
  BehemothSpitter = 236,
  SpitterSpawner = 237,
  Defender = 238,
  Distractor = 239,
  Destroyer = 240,
  AcidSplashFireSpitterBehemoth = 241,
  AcidSplashFireSpitterBig = 242,
  AcidSplashFireSpitterMedium = 243,
  AcidSplashFireSpitterSmall = 244,
  AcidSplashFireWormBehemoth = 245,
  AcidSplashFireWormBig = 246,
  AcidSplashFireWormMedium = 247,
  AcidSplashFireWormSmall = 248,
  AcidStickerBehemoth = 249,
  AcidStickerBig = 250,
  AcidStickerMedium = 251,
  AcidStickerSmall = 252,
  AcidStreamSpitterBehemoth = 253,
  AcidStreamSpitterBig = 254,
  AcidStreamSpitterMedium = 255,
  AcidStreamSpitterSmall = 256,
  AcidStreamWormBehemoth = 257,
  AcidStreamWormBig = 258,
  AcidStreamWormMedium = 259,
  AcidStreamWormSmall = 260,
  ArtilleryCannonMuzzleFlash = 261,
  ArtilleryFlare = 262,
  ArtilleryProjectile = 263,
  AtomicBombWave = 264,
  AtomicRocket = 265,
  BigArtilleryExplosion = 266,
  BigExplosion = 267,
  BigShipWreckGrass = 268,
  BloodExplosionBig = 269,
  BloodExplosionHuge = 270,
  BloodExplosionSmall = 271,
  BloodFountain = 272,
  BloodFountainBig = 273,
  BloodParticle = 274,
  BlueLaser = 275,
  BranchParticle = 276,
  BrownAsterisk = 277,
  BrownCaneCluster = 278,
  BrownCaneSingle = 279,
  BrownCarpetGrass = 280,
  BrownCoralMini = 281,
  BrownFluff = 282,
  BrownFluffDry = 283,
  BrownHairyGrass = 284,
  CannonProjectile = 285,
  CharacterCorpse = 286,
  CliffExplosives = 287,
  ClusterGrenade = 288,
  CoalParticle = 289,
  CompiLogisticsChest = 290,
  CompiSpeechBubble = 291,
  CopperOreParticle = 292,
  DeconstructibleTileProxy = 293,
  DefenderCapsule = 294,
  DestroyerCapsule = 295,
  DistractorCapsule = 296,
  DummyFlameThrowerExplosion = 297,
  ElectricBeam = 298,
  ElectricBeamNoSound = 299,
  EntityGhost = 300,
  Explosion = 301,
  ExplosionGunshot = 302,
  ExplosionGunshotSmall = 303,
  ExplosionHit = 304,
  ExplosionRemnantsParticle = 305,
  ExplosiveCannonProjectile = 306,
  ExplosiveRocket = 307,
  ExplosiveUraniumCannonProjectile = 308,
  FakeSelectionBox2x2 = 309,
  FireFlame = 310,
  FireFlameOnTree = 311,
  FireSticker = 312,
  FlamethrowerFireStream = 313,
  FlyingText = 314,
  Garballo = 315,
  GarballoMiniDry = 316,
  GreenAsterisk = 317,
  GreenBushMini = 318,
  GreenCarpetGrass = 319,
  GreenCoralMini = 320,
  GreenHairyGrass = 321,
  GreenPita = 322,
  GreenPitaMini = 323,
  GreenSmallGrass = 324,
  Grenade = 325,
  GroundExplosion = 326,
  HandheldFlamethrowerFireStream = 327,
  HighlightBox = 328,
  IronOreParticle = 329,
  ItemOnGround = 330,
  ItemRequestProxy = 331,
  Laser = 332,
  LaserBeam = 333,
  LaserBubble = 334,
  LeafParticle = 335,
  MassiveExplosion = 336,
  MediumExplosion = 337,
  OrangeArrowWithCircle = 338,
  OrangeCoralMini = 339,
  PiercingShotgunPellet = 340,
  PoisonCapsule = 341,
  PoisonCloud = 342,
  RailgunBeam = 343,
  RedAsterisk = 344,
  Rocket = 345,
  RocketSiloRocket = 346,
  RocketSiloRocketShadow = 347,
  RootA = 348,
  RootB = 349,
  ShallowWaterDropletParticle = 350,
  ShellParticle = 351,
  ShotgunPellet = 352,
  SlowdownCapsule = 353,
  SlowdownSticker = 354,
  SmallShipWreckGrass = 355,
  SmokeForMigration = 356,
  StoneParticle = 357,
  StunSticker = 358,
  TankFlamethrowerFireStream = 359,
  TileGhost = 360,
  TileProxy = 361,
  TreeDyingProxy = 362,
  TreeProxy = 363,
  TutorialFlyingText = 364,
  UraniumCannonExplosion = 365,
  UraniumCannonProjectile = 366,
  UraniumCannonShellExplosion = 367,
  WaterSplash = 368,
  WoodenParticle = 369,
  BaitChest = 370,
  CrudeOil = 371,
  Coal = 372,
  CopperOre = 373,
  IronOre = 374,
  Stone = 375,
  UraniumOre = 376,
  CutsceneGunTurret = 377,
  BlueChest = 378,
  CompiRoboport = 379,
  Market = 380,
  HiddenElectricEnergyInterface = 381,
  RedChest = 382,
}

// Version: 0.17.69
// Alt method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum Equipment {
  BatteryEquipment = 1,
  BatteryMk2Equipment = 2,
  DischargeDefenseEquipment = 3,
  EnergyShieldEquipment = 4,
  EnergyShieldMk2Equipment = 5,
  ExoskeletonEquipment = 6,
  FusionReactorEquipment = 7,
  NightVisionEquipment = 8,
  PersonalLaserDefenseEquipment = 9,
  PersonalRoboportEquipment = 10,
  PersonalRoboportMk2Equipment = 11,
  SolarPanelEquipment = 12,
  BeltImmunityEquipment = 13,
}

// Version: 0.17.69
// Extraction method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum Fluid {
  Water = 1,
  CrudeOil = 2,
  Steam = 3,
  HeavyOil = 4,
  LightOil = 5,
  PetroleumGas = 6,
  SulfuricAcid = 7,
  Lubricant = 8,
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum ForceId {
  Player = 1,
  Enemy = 2,
  Neutral = 3,
}

// Version: 0.17.69
// Extraction method: from level.dat in save file, secion "item", encoded as string-u16 pairs
// Alt method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum Item {
  WoodenChest = 1,
  IronChest = 2,
  SteelChest = 3,
  CompilatronChest = 4,
  StorageTank = 5,
  TransportBelt = 6,
  FastTransportBelt = 7,
  ExpressTransportBelt = 8,
  UndergroundBelt = 9,
  FastUndergroundBelt = 10,
  ExpressUndergroundBelt = 11,
  Splitter = 12,
  FastSplitter = 13,
  ExpressSplitter = 14,
  Loader = 15,
  FastLoader = 16,
  ExpressLoader = 17,
  BurnerInserter = 18,
  Inserter = 19,
  LongHandedInserter = 20,
  FastInserter = 21,
  FilterInserter = 22,
  StackInserter = 23,
  StackFilterInserter = 24,
  SmallElectricPole = 25,
  MediumElectricPole = 26,
  BigElectricPole = 27,
  Substation = 28,
  Pipe = 29,
  PipeToGround = 30,
  Pump = 31,
  Rail = 32,
  TrainStop = 33,
  RailSignal = 34,
  RailChainSignal = 35,
  Locomotive = 36,
  CargoWagon = 37,
  FluidWagon = 38,
  ArtilleryWagon = 39,
  Car = 40,
  Tank = 41,
  SmallPlane = 42,
  LogisticRobot = 43,
  ConstructionRobot = 44,
  LogisticChestActiveProvider = 45,
  LogisticChestPassiveProvider = 46,
  LogisticChestStorage = 47,
  LogisticChestBuffer = 48,
  LogisticChestRequester = 49,
  Roboport = 50,
  SmallLamp = 51,
  RedWire = 52,
  GreenWire = 53,
  ArithmeticCombinator = 54,
  DeciderCombinator = 55,
  ConstantCombinator = 56,
  PowerSwitch = 57,
  ProgrammableSpeaker = 58,
  StoneBrick = 59,
  Concrete = 60,
  HazardConcrete = 61,
  RefinedConcrete = 62,
  RefinedHazardConcrete = 63,
  Landfill = 64,
  CliffExplosives = 65,
  DummySteelAxe = 66,
  RepairPack = 67,
  Blueprint = 68,
  DeconstructionPlanner = 69,
  UpgradePlanner = 70,
  BlueprintBook = 71,
  CopyPasteTool = 72,
  CutPasteTool = 73,
  Boiler = 74,
  SteamEngine = 75,
  SteamTurbine = 76,
  SolarPanel = 77,
  Accumulator = 78,
  ElectricEnergyInterface = 79,
  HeatInterface = 80,
  NuclearReactor = 81,
  HeatExchanger = 82,
  HeatPipe = 83,
  BurnerMiningDrill = 84,
  ElectricMiningDrill = 85,
  OffshorePump = 86,
  Pumpjack = 87,
  StoneFurnace = 88,
  SteelFurnace = 89,
  ElectricFurnace = 90,
  AssemblingMachine1 = 91,
  AssemblingMachine2 = 92,
  AssemblingMachine3 = 93,
  OilRefinery = 94,
  ChemicalPlant = 95,
  Centrifuge = 96,
  Lab = 97,
  Beacon = 98,
  SpeedModule = 99,
  SpeedModule2 = 100,
  SpeedModule3 = 101,
  EffectivityModule = 102,
  EffectivityModule2 = 103,
  EffectivityModule3 = 104,
  ProductivityModule = 105,
  ProductivityModule2 = 106,
  ProductivityModule3 = 107,
  CrashSiteAssemblingMachine1Broken = 108,
  CrashSiteAssemblingMachine1Repaired = 109,
  CrashSiteAssemblingMachine2Broken = 110,
  CrashSiteAssemblingMachine2Repaired = 111,
  CrashSiteChest1 = 112,
  CrashSiteChest2 = 113,
  CrashSiteElectricPole = 114,
  CrashSiteGenerator = 115,
  CrashSiteLabBroken = 116,
  CrashSiteLabRepaired = 117,
  Wood = 118,
  Coal = 119,
  Stone = 120,
  IronOre = 121,
  CopperOre = 122,
  UraniumOre = 123,
  RawFish = 124,
  IronPlate = 125,
  CopperPlate = 126,
  SolidFuel = 127,
  SteelPlate = 128,
  PlasticBar = 129,
  Sulfur = 130,
  Battery = 131,
  Explosives = 132,
  CrudeOilBarrel = 133,
  HeavyOilBarrel = 134,
  LightOilBarrel = 135,
  LubricantBarrel = 136,
  PetroleumGasBarrel = 137,
  SulfuricAcidBarrel = 138,
  WaterBarrel = 139,
  CopperCable = 140,
  IronStick = 141,
  IronGearWheel = 142,
  EmptyBarrel = 143,
  ElectronicCircuit = 144,
  AdvancedCircuit = 145,
  ProcessingUnit = 146,
  EngineUnit = 147,
  ElectricEngineUnit = 148,
  FlyingRobotFrame = 149,
  Satellite = 150,
  RocketControlUnit = 151,
  LowDensityStructure = 152,
  RocketFuel = 153,
  RocketPart = 154,
  NuclearFuel = 155,
  Uranium235 = 156,
  Uranium238 = 157,
  UraniumFuelCell = 158,
  UsedUpUraniumFuelCell = 159,
  AutomationSciencePack = 160,
  LogisticSciencePack = 161,
  MilitarySciencePack = 162,
  ChemicalSciencePack = 163,
  ProductionSciencePack = 164,
  UtilitySciencePack = 165,
  SpaceSciencePack = 166,
  Coin = 167,
  Pistol = 168,
  SubmachineGun = 169,
  TankMachineGun = 170,
  VehicleMachineGun = 171,
  TankFlamethrower = 172,
  Shotgun = 173,
  CombatShotgun = 174,
  Railgun = 175,
  RocketLauncher = 176,
  Flamethrower = 177,
  LandMine = 178,
  ArtilleryWagonCannon = 179,
  TankCannon = 180,
  FirearmMagazine = 181,
  PiercingRoundsMagazine = 182,
  UraniumRoundsMagazine = 183,
  ShotgunShell = 184,
  PiercingShotgunShell = 185,
  RailgunDart = 186,
  CannonShell = 187,
  ExplosiveCannonShell = 188,
  UraniumCannonShell = 189,
  ExplosiveUraniumCannonShell = 190,
  ArtilleryShell = 191,
  Rocket = 192,
  ExplosiveRocket = 193,
  AtomicBomb = 194,
  FlamethrowerAmmo = 195,
  Grenade = 196,
  ClusterGrenade = 197,
  PoisonCapsule = 198,
  SlowdownCapsule = 199,
  DefenderCapsule = 200,
  DistractorCapsule = 201,
  DestroyerCapsule = 202,
  DischargeDefenseRemote = 203,
  ArtilleryTargetingRemote = 204,
  LightArmor = 205,
  HeavyArmor = 206,
  ModularArmor = 207,
  PowerArmor = 208,
  PowerArmorMk2 = 209,
  SolarPanelEquipment = 210,
  FusionReactorEquipment = 211,
  EnergyShieldEquipment = 212,
  EnergyShieldMk2Equipment = 213,
  BatteryEquipment = 214,
  BatteryMk2Equipment = 215,
  PersonalLaserDefenseEquipment = 216,
  DischargeDefenseEquipment = 217,
  BeltImmunityEquipment = 218,
  ExoskeletonEquipment = 219,
  PersonalRoboportEquipment = 220,
  PersonalRoboportMk2Equipment = 221,
  NightVisionEquipment = 222,
  StoneWall = 223,
  Gate = 224,
  GunTurret = 225,
  LaserTurret = 226,
  FlamethrowerTurret = 227,
  ArtilleryTurret = 228,
  Radar = 229,
  RocketSilo = 230,
  Computer = 231,
  PlayerPort = 232,
  SelectionTool = 233,
  ItemWithInventory = 234,
  ItemWithLabel = 235,
  ItemWithTags = 236,
  SimpleEntityWithForce = 237,
  SimpleEntityWithOwner = 238,
  InfinityChest = 239,
  InfinityPipe = 240,
}

// Version: 0.17.69
// Extraction method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum ItemGroup {
  Environment = 1,
  Enemies = 2,
  Logistics = 3,
  Production = 4,
  IntermediateProducts = 5,
  Combat = 6,
  Fluids = 7,
  Signals = 8,
  Other = 9,
}

// Version: 0.17.69
// Extraction method: from level.dat in save file, secion "recipe", encoded as string-u16 pairs
// Alt method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum Recipe {
  Accumulator = 1,
  AdvancedCircuit = 2,
  ArithmeticCombinator = 3,
  ArtilleryShell = 4,
  ArtilleryTargetingRemote = 5,
  ArtilleryTurret = 6,
  ArtilleryWagon = 7,
  AssemblingMachine1 = 8,
  AssemblingMachine2 = 9,
  AssemblingMachine3 = 10,
  AtomicBomb = 11,
  AutomationSciencePack = 12,
  Battery = 13,
  BatteryEquipment = 14,
  BatteryMk2Equipment = 15,
  Beacon = 16,
  BeltImmunityEquipment = 17,
  BigElectricPole = 18,
  Boiler = 19,
  BurnerInserter = 20,
  BurnerMiningDrill = 21,
  CannonShell = 22,
  Car = 23,
  CargoWagon = 24,
  Centrifuge = 25,
  ChemicalPlant = 26,
  ChemicalSciencePack = 27,
  CliffExplosives = 28,
  ClusterGrenade = 29,
  CombatShotgun = 30,
  Concrete = 31,
  ConstantCombinator = 32,
  ConstructionRobot = 33,
  CopperCable = 34,
  CopperPlate = 35,
  DeciderCombinator = 36,
  DefenderCapsule = 37,
  DestroyerCapsule = 38,
  DischargeDefenseEquipment = 39,
  DischargeDefenseRemote = 40,
  DistractorCapsule = 41,
  EffectivityModule = 42,
  EffectivityModule2 = 43,
  EffectivityModule3 = 44,
  ElectricEnergyInterface = 45,
  ElectricEngineUnit = 46,
  ElectricFurnace = 47,
  ElectricMiningDrill = 48,
  ElectronicCircuit = 49,
  EmptyBarrel = 50,
  EnergyShieldEquipment = 51,
  EnergyShieldMk2Equipment = 52,
  EngineUnit = 53,
  ExoskeletonEquipment = 54,
  ExplosiveCannonShell = 55,
  ExplosiveRocket = 56,
  ExplosiveUraniumCannonShell = 57,
  Explosives = 58,
  ExpressLoader = 59,
  ExpressSplitter = 60,
  ExpressTransportBelt = 61,
  ExpressUndergroundBelt = 62,
  FastInserter = 63,
  FastLoader = 64,
  FastSplitter = 65,
  FastTransportBelt = 66,
  FastUndergroundBelt = 67,
  FilterInserter = 68,
  FirearmMagazine = 69,
  Flamethrower = 70,
  FlamethrowerAmmo = 71,
  FlamethrowerTurret = 72,
  FluidWagon = 73,
  FlyingRobotFrame = 74,
  FusionReactorEquipment = 75,
  Gate = 76,
  GreenWire = 77,
  Grenade = 78,
  GunTurret = 79,
  HazardConcrete = 80,
  HeatExchanger = 81,
  HeatPipe = 82,
  HeavyArmor = 83,
  Inserter = 84,
  IronChest = 85,
  IronGearWheel = 86,
  IronPlate = 87,
  IronStick = 88,
  Lab = 89,
  LandMine = 90,
  Landfill = 91,
  LaserTurret = 92,
  LightArmor = 93,
  Loader = 94,
  Locomotive = 95,
  LogisticChestActiveProvider = 96,
  LogisticChestBuffer = 97,
  LogisticChestPassiveProvider = 98,
  LogisticChestRequester = 99,
  LogisticChestStorage = 100,
  LogisticRobot = 101,
  LogisticSciencePack = 102,
  LongHandedInserter = 103,
  LowDensityStructure = 104,
  Lubricant = 105,
  MediumElectricPole = 106,
  MilitarySciencePack = 107,
  ModularArmor = 108,
  NightVisionEquipment = 109,
  NuclearFuel = 110,
  NuclearReactor = 111,
  OffshorePump = 112,
  OilRefinery = 113,
  PersonalLaserDefenseEquipment = 114,
  PersonalRoboportEquipment = 115,
  PersonalRoboportMk2Equipment = 116,
  PiercingRoundsMagazine = 117,
  PiercingShotgunShell = 118,
  Pipe = 119,
  PipeToGround = 120,
  Pistol = 121,
  PlasticBar = 122,
  PlayerPort = 123,
  PoisonCapsule = 124,
  PowerArmor = 125,
  PowerArmorMk2 = 126,
  PowerSwitch = 127,
  ProcessingUnit = 128,
  ProductionSciencePack = 129,
  ProductivityModule = 130,
  ProductivityModule2 = 131,
  ProductivityModule3 = 132,
  ProgrammableSpeaker = 133,
  Pump = 134,
  Pumpjack = 135,
  Radar = 136,
  Rail = 137,
  RailChainSignal = 138,
  RailSignal = 139,
  Railgun = 140,
  RailgunDart = 141,
  RedWire = 142,
  RefinedConcrete = 143,
  RefinedHazardConcrete = 144,
  RepairPack = 145,
  Roboport = 146,
  Rocket = 147,
  RocketControlUnit = 148,
  RocketFuel = 149,
  RocketLauncher = 150,
  RocketPart = 151,
  RocketSilo = 152,
  Satellite = 153,
  Shotgun = 154,
  ShotgunShell = 155,
  SlowdownCapsule = 156,
  SmallElectricPole = 157,
  SmallLamp = 158,
  SmallPlane = 159,
  SolarPanel = 160,
  SolarPanelEquipment = 161,
  SpeedModule = 162,
  SpeedModule2 = 163,
  SpeedModule3 = 164,
  Splitter = 165,
  StackFilterInserter = 166,
  StackInserter = 167,
  SteamEngine = 168,
  SteamTurbine = 169,
  SteelChest = 170,
  SteelFurnace = 171,
  SteelPlate = 172,
  StoneBrick = 173,
  StoneFurnace = 174,
  StoneWall = 175,
  StorageTank = 176,
  SubmachineGun = 177,
  Substation = 178,
  Sulfur = 179,
  SulfuricAcid = 180,
  Tank = 181,
  TrainStop = 182,
  TransportBelt = 183,
  UndergroundBelt = 184,
  UraniumCannonShell = 185,
  UraniumFuelCell = 186,
  UraniumRoundsMagazine = 187,
  UtilitySciencePack = 188,
  WoodenChest = 189,
  BasicOilProcessing = 190,
  AdvancedOilProcessing = 191,
  CoalLiquefaction = 192,
  FillCrudeOilBarrel = 193,
  FillHeavyOilBarrel = 194,
  FillLightOilBarrel = 195,
  FillLubricantBarrel = 196,
  FillPetroleumGasBarrel = 197,
  FillSulfuricAcidBarrel = 198,
  FillWaterBarrel = 199,
  HeavyOilCracking = 200,
  LightOilCracking = 201,
  SolidFuelFromLightOil = 202,
  SolidFuelFromPetroleumGas = 203,
  SolidFuelFromHeavyOil = 204,
  EmptyCrudeOilBarrel = 205,
  EmptyHeavyOilBarrel = 206,
  EmptyLightOilBarrel = 207,
  EmptyLubricantBarrel = 208,
  EmptyPetroleumGasBarrel = 209,
  EmptySulfuricAcidBarrel = 210,
  EmptyWaterBarrel = 211,
  UraniumProcessing = 212,
  NuclearFuelReprocessing = 213,
  KovarexEnrichmentProcess = 214,
}

// Version: 0.17.69
// Extraction method: from level.dat in save file, secion "technology", encoded as string-u16 pairs
// Alt method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum Technology {
  Automation = 1,
  Automation2 = 2,
  Automation3 = 3,
  Electronics = 4,
  FastInserter = 5,
  AdvancedElectronics = 6,
  AdvancedElectronics2 = 7,
  CircuitNetwork = 8,
  Explosives = 9,
  Logistics = 10,
  Logistics2 = 11,
  Logistics3 = 12,
  BasicOptics = 13,
  Optics = 14,
  Laser = 15,
  SolarEnergy = 16,
  Turrets = 17,
  LaserTurrets = 18,
  StoneWalls = 19,
  Gates = 20,
  Engine = 21,
  ElectricEngine = 22,
  Lubricant = 23,
  Battery = 24,
  Landfill = 25,
  BrakingForce1 = 26,
  BrakingForce2 = 27,
  BrakingForce3 = 28,
  BrakingForce4 = 29,
  BrakingForce5 = 30,
  BrakingForce6 = 31,
  BrakingForce7 = 32,
  ActiveDefense = 33,
  AnalyseShip = 34,
  BasicElectronics = 35,
  BasicLogistics = 36,
  BasicMapping = 37,
  BasicMilitary = 38,
  BasicMining = 39,
  ChemicalSciencePack = 40,
  DemoAutomationUpgrade = 41,
  DemoGates = 42,
  DemoLogistics = 43,
  DemoMilitaryEquipment = 44,
  DemoMunitionsUpgrade = 45,
  DemoSciencePack = 46,
  DemoSteelFurnace = 47,
  DemoSteelPoles = 48,
  DemoSteelProcessing = 49,
  ElectricInserter = 50,
  ElectricMining = 51,
  ImprovedEquipment = 52,
  LogisticSciencePack = 53,
  MilitarySciencePack = 54,
  PassiveDefense = 55,
  ProductionSciencePack = 56,
  Radar = 57,
  RepairTech = 58,
  SpaceSciencePack = 59,
  SteelProcessing = 60,
  UtilitySciencePack = 61,
  AdvancedMaterialProcessing = 62,
  SteelAxe = 63,
  AdvancedMaterialProcessing2 = 64,
  Concrete = 65,
  ElectricEnergyAccumulators = 66,
  ElectricEnergyDistribution1 = 67,
  ElectricEnergyDistribution2 = 68,
  Railway = 69,
  FluidWagon = 70,
  AutomatedRailTransportation = 71,
  RailSignals = 72,
  Robotics = 73,
  ConstructionRobotics = 74,
  LogisticRobotics = 75,
  LogisticSystem = 76,
  PersonalRoboportEquipment = 77,
  PersonalRoboportMk2Equipment = 78,
  CharacterLogisticSlots1 = 79,
  CharacterLogisticSlots2 = 80,
  CharacterLogisticSlots3 = 81,
  CharacterLogisticSlots4 = 82,
  CharacterLogisticSlots5 = 83,
  CharacterLogisticSlots6 = 84,
  CharacterLogisticTrashSlots1 = 85,
  WorkerRobotsSpeed1 = 86,
  CharacterLogisticTrashSlots2 = 87,
  WorkerRobotsSpeed2 = 88,
  AutoCharacterLogisticTrashSlots = 89,
  CharacterLogisticTrashSlots3 = 90,
  WorkerRobotsSpeed3 = 91,
  CharacterLogisticTrashSlots4 = 92,
  WorkerRobotsSpeed4 = 93,
  CharacterLogisticTrashSlots5 = 94,
  DemoProductivity1 = 95,
  MiningProductivity1 = 96,
  MiningProductivity2 = 97,
  MiningProductivity3 = 98,
  MiningProductivity4 = 99,
  WorkerRobotsSpeed5 = 100,
  WorkerRobotsSpeed6 = 101,
  WorkerRobotsStorage1 = 102,
  WorkerRobotsStorage2 = 103,
  WorkerRobotsStorage3 = 104,
  Toolbelt = 105,
  ResearchSpeed1 = 106,
  ResearchSpeed2 = 107,
  ResearchSpeed3 = 108,
  ResearchSpeed4 = 109,
  ResearchSpeed5 = 110,
  ResearchSpeed6 = 111,
  StackInserter = 112,
  InserterCapacityBonus1 = 113,
  InserterCapacityBonus2 = 114,
  InserterCapacityBonus3 = 115,
  InserterCapacityBonus4 = 116,
  InserterCapacityBonus5 = 117,
  InserterCapacityBonus6 = 118,
  InserterCapacityBonus7 = 119,
  OilProcessing = 120,
  FluidHandling = 121,
  AdvancedOilProcessing = 122,
  CoalLiquefaction = 123,
  SulfurProcessing = 124,
  Plastics = 125,
  Artillery = 126,
  Military = 127,
  AtomicBomb = 128,
  Military2 = 129,
  UraniumAmmo = 130,
  Military3 = 131,
  Military4 = 132,
  Automobilism = 133,
  Flammables = 134,
  Flamethrower = 135,
  Tanks = 136,
  LandMine = 137,
  Rocketry = 138,
  ExplosiveRocketry = 139,
  DemoShootingSpeed1 = 140,
  DemoShootingSpeed4 = 141,
  EnergyWeaponsDamage1 = 142,
  RefinedFlammables1 = 143,
  StrongerExplosives1 = 144,
  WeaponShootingSpeed1 = 145,
  ArtilleryShellRange1 = 146,
  ArtilleryShellSpeed1 = 147,
  PhysicalProjectileDamage1 = 148,
  EnergyWeaponsDamage2 = 149,
  PhysicalProjectileDamage2 = 150,
  RefinedFlammables2 = 151,
  StrongerExplosives2 = 152,
  WeaponShootingSpeed2 = 153,
  EnergyWeaponsDamage3 = 154,
  PhysicalProjectileDamage3 = 155,
  RefinedFlammables3 = 156,
  StrongerExplosives3 = 157,
  WeaponShootingSpeed3 = 158,
  EnergyWeaponsDamage4 = 159,
  PhysicalProjectileDamage4 = 160,
  RefinedFlammables4 = 161,
  StrongerExplosives4 = 162,
  WeaponShootingSpeed4 = 163,
  EnergyWeaponsDamage5 = 164,
  PhysicalProjectileDamage5 = 165,
  RefinedFlammables5 = 166,
  StrongerExplosives5 = 167,
  WeaponShootingSpeed5 = 168,
  EnergyWeaponsDamage6 = 169,
  EnergyWeaponsDamage7 = 170,
  PhysicalProjectileDamage6 = 171,
  PhysicalProjectileDamage7 = 172,
  RefinedFlammables6 = 173,
  RefinedFlammables7 = 174,
  StrongerExplosives6 = 175,
  StrongerExplosives7 = 176,
  WeaponShootingSpeed6 = 177,
  LaserTurretSpeed1 = 178,
  LaserTurretSpeed2 = 179,
  LaserTurretSpeed3 = 180,
  LaserTurretSpeed4 = 181,
  LaserTurretSpeed5 = 182,
  LaserTurretSpeed6 = 183,
  LaserTurretSpeed7 = 184,
  CombatRobotics = 185,
  CombatRobotics2 = 186,
  CombatRobotics3 = 187,
  FollowerRobotCount1 = 188,
  FollowerRobotCount2 = 189,
  FollowerRobotCount3 = 190,
  FollowerRobotCount4 = 191,
  FollowerRobotCount5 = 192,
  FollowerRobotCount6 = 193,
  FollowerRobotCount7 = 194,
  KovarexEnrichmentProcess = 195,
  NuclearFuelReprocessing = 196,
  NuclearPower = 197,
  UraniumProcessing = 198,
  HeavyArmor = 199,
  ModularArmor = 200,
  PowerArmor = 201,
  PowerArmorMk2 = 202,
  EnergyShieldEquipment = 203,
  EnergyShieldMk2Equipment = 204,
  NightVisionEquipment = 205,
  BeltImmunityEquipment = 206,
  ExoskeletonEquipment = 207,
  BatteryEquipment = 208,
  BatteryMk2Equipment = 209,
  SolarPanelEquipment = 210,
  FusionReactorEquipment = 211,
  PersonalLaserDefenseEquipment = 212,
  DischargeDefenseEquipment = 213,
  Modules = 214,
  SpeedModule = 215,
  SpeedModule2 = 216,
  SpeedModule3 = 217,
  ProductivityModule = 218,
  ProductivityModule2 = 219,
  ProductivityModule3 = 220,
  EffectivityModule = 221,
  EffectivityModule2 = 222,
  EffectivityModule3 = 223,
  EffectTransmission = 224,
  LowDensityStructure = 225,
  RocketControlUnit = 226,
  RocketFuel = 227,
  RocketSilo = 228,
  CliffExplosives = 229,
}


// Version: 0.17.69
// Extraction method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU8)]
pub enum Tile {
  Concrete = 1,
  Deepwater = 2,
  DeepwaterGreen = 3,
  Dirt1 = 4,
  Dirt2 = 5,
  Dirt3 = 6,
  Dirt4 = 7,
  Dirt5 = 8,
  Dirt6 = 9,
  Dirt7 = 10,
  DryDirt = 11,
  Grass1 = 12,
  Grass2 = 13,
  Grass3 = 14,
  Grass4 = 15,
  HazardConcreteLeft = 16,
  HazardConcreteRight = 17,
  LabDark1 = 18,
  LabDark2 = 19,
  LabWhite = 20,
  Landfill = 21,
  OutOfMap = 22,
  RedDesert0 = 23,
  RedDesert1 = 24,
  RedDesert2 = 25,
  RedDesert3 = 26,
  RefinedConcrete = 27,
  RefinedHazardConcreteLeft = 28,
  RefinedHazardConcreteRight = 29,
  Sand1 = 30,
  Sand2 = 31,
  Sand3 = 32,
  StonePath = 33,
  TutorialGrid = 34,
  Water = 35,
  WaterGreen = 36,
  WaterMud = 37,
  WaterShallow = 38,
}

// Version: 0.17.69
// Extraction method: use command in readme
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Primitive, ReadWriteEnumU16)]
pub enum VirtualSignal {
  SignalEverything = 1,
  SignalAnything = 2,
  SignalEach = 3,
  Signal0 = 4,
  Signal1 = 5,
  Signal2 = 6,
  Signal3 = 7,
  Signal4 = 8,
  Signal5 = 9,
  Signal6 = 10,
  Signal7 = 11,
  Signal8 = 12,
  Signal9 = 13,
  SignalA = 14,
  SignalB = 15,
  SignalC = 16,
  SignalD = 17,
  SignalE = 18,
  SignalF = 19,
  SignalG = 20,
  SignalH = 21,
  SignalI = 22,
  SignalJ = 23,
  SignalK = 24,
  SignalL = 25,
  SignalM = 26,
  SignalN = 27,
  SignalO = 28,
  SignalP = 29,
  SignalQ = 30,
  SignalR = 31,
  SignalS = 32,
  SignalT = 33,
  SignalU = 34,
  SignalV = 35,
  SignalW = 36,
  SignalX = 37,
  SignalY = 38,
  SignalZ = 39,
  SignalRed = 40,
  SignalGreen = 41,
  SignalBlue = 42,
  SignalYellow = 43,
  SignalPink = 44,
  SignalCyan = 45,
  SignalWhite = 46,
  SignalGrey = 47,
  SignalBlack = 48,
  SignalCheck = 49,
  SignalInfo = 50,
  SignalDot = 51,
}
